user nginx;
worker_processes auto;
events { worker_connections 2048; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    tcp_nopush    on;
    keepalive_timeout 65;
    client_max_body_size 60M;
    gzip on;
    gzip_types text/plain application/json application/javascript text/css application/xml;

    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html/public;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass app:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_read_timeout 300;
        }

        location ~ /\.(?!well-known).* { deny all; }
    }
}
