import { useEffect, useMemo, useRef, useState, type RefObject } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { z } from "zod";
import { supabase } from "@/integrations/supabase/client";
import { db } from "@/lib/db";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Plus, Eye, Search, Trash2, Pencil, AlertTriangle, Loader2, Download, Upload } from "lucide-react";
import { TruncateText } from "@/components/ui/truncate-text";
import { EditButton, DeleteButton, ViewButton } from "@/components/ui/action-icon-button";
import * as XLSX from "xlsx";
import { normalizeFarmerCode } from "@/lib/farmerCode";
import { parseDagSearchTokens } from "@/lib/dagNumbers";
import { formatId5 } from "@/lib/idFormat";
import { useUnsavedFormGuard } from "@/hooks/useUnsavedFormGuard";

const FARMER_TEMPLATE_HEADERS = [
  "name_en", "name_bn", "father_name", "mother_name", "nid", "mobile",
  "member_no", "is_voter", "status", "village", "address",
  "division", "district", "upazila", "union", "ward", "village_loc", "mouza",
];

function downloadFarmerTemplate() {
  const ws = XLSX.utils.aoa_to_sheet([
    FARMER_TEMPLATE_HEADERS,
    [
      "Karim Uddin", "করিম উদ্দিন", "Abdul", "Salma", "1234567890123", "01700000000", // i18n-ignore
      "", "false", "active", "Free-text village", "Holding/road",
      "Dhaka", "Dhaka", "Savar", "Aminbazar", "Ward 1", "Bagbari", "Mouza A",
    ],
  ]);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Farmers");
  XLSX.writeFile(wb, "farmer-import-template.xlsx");
}
import { money } from "@/lib/format";
import { LocationPicker, LocationValue } from "@/components/locations/LocationPicker";
import { useLang } from "@/i18n/LanguageProvider";
import { toast } from "sonner";
import { useAuth } from "@/auth/AuthProvider";
import { validateLocationChain, parseLocationDbError, type LocationLevel } from "@/lib/locationValidation";
import { toFarmerUpdatePayload } from "@/lib/farmerUpdateMapper";
import { VoterHistoryDialog } from "@/components/farmers/VoterHistoryDialog";
import { History } from "lucide-react";

/**
 * Unified Voter / Savings Account field.
 * voter_number থাকলেই active সদস্য — আলাদা toggle নেই।
 * খালি থাকলে "Generate" বাটনে অটো নম্বর তৈরি হবে।
 */
function VoterSavingsField({ f, setF, disabled, isSuper }: { f: any; setF: (n: any) => void; disabled: boolean; isSuper: boolean }) {
  const [generating, setGenerating] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const { t, tx } = useLang();
  const hasNumber = !!f.voter_number;
  // Existing voter_number is immutable for non-super (DB trigger). Only super can edit existing.
  const inputDisabled = disabled || generating || (hasNumber && !isSuper && !!f.id);

  async function generate() {
    setGenerating(true);
    try {
      const { data, error } = await db.rpc("generate_account_number" as any, {
        _office_id: f.office_id || null,
      });
      if (error) { toast.error(error.message); return; }
      const acc = String(data ?? "");
      setF({ ...f, voter_number: acc, account_number: acc, is_voter: true });
      toast.success(t("savingsAccountAutoGenerated"));
    } finally { setGenerating(false); }
  }

  return (
    <div className="col-span-2">
      <Label>{t("voterSavingsAccount")} <span className="text-xs text-muted-foreground">(Savings Member A/C No)</span></Label>
      <div className="flex gap-2">
        <Input
          value={f.voter_number || ""}
          disabled={inputDisabled}
          maxLength={5}
          inputMode="numeric"
          placeholder={tx("Leave blank and press Generate", "খালি রাখলে Generate চাপুন")}
          onChange={(e) => {
            const v = e.target.value.replace(/\D/g, "").slice(0, 5);
            setF({ ...f, voter_number: v, account_number: v, is_voter: !!v });
          }}
          data-testid="voter-number-input"
        />
        {!hasNumber && (
          <Button type="button" variant="outline" onClick={generate} disabled={disabled || generating}>
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : "Generate"}
          </Button>
        )}
        {f.id && (
          <Button type="button" variant="ghost" size="sm" onClick={() => setHistoryOpen(true)} title={t("viewHistory")}>
            <History className="h-4 w-4" />
          </Button>
        )}
      </div>
      <p className="mt-1 text-xs text-muted-foreground">
        {hasNumber ? `✓ ${t("voterSavingsActive")}` : tx("If a number is set, will be auto-treated as a Savings Member", "নম্বর থাকলেই স্বয়ংক্রিয়ভাবে সেভিং সদস্য হিসেবে গণ্য হবে")}
      </p>
      <VoterHistoryDialog farmerId={f.id ?? null} open={historyOpen} onOpenChange={setHistoryOpen} />
    </div>
  );
}

/** Farmer ID field — always visible, auto-generated on add, super admin can override. */
function FarmerIdField({ f, setF, disabled, isSuper, currentId }: { f: any; setF: (n: any) => void; disabled: boolean; isSuper: boolean; currentId?: string | null }) {
  const { tx } = useLang();
  const [checking, setChecking] = useState(false);
  const [dupErr, setDupErr] = useState<string | null>(null);
  const [fmtErr, setFmtErr] = useState<string | null>(null);
  const tRef = useRef<any>(null);

  async function onChange(v: string) {
    setF({ ...f, member_no: v });
    setDupErr(null);
    setFmtErr(null);
    if (tRef.current) clearTimeout(tRef.current);
    if (!v.trim()) return;
    setChecking(true);
    tRef.current = setTimeout(async () => {
      const { data, error } = await db.rpc("member_no_exists" as any, {
        _member_no: v.trim(), _exclude_id: currentId ?? null,
      });
      setChecking(false);
      if (!error && data === true) setDupErr(tx("This Farmer ID is already in use.", "এই Farmer ID আগে থেকেই ব্যবহৃত।"));
    }, 350);
  }

  function onBlur() {
    const v = (f.member_no ?? "").trim();
    if (!v) return;
    const r = normalizeFarmerCode(v);
    if (r.ok === false) { setFmtErr(r.error); return; }
    if (r.value !== v) setF({ ...f, member_no: r.value });
  }

  return (
    <div className="col-span-2">
      <Label className={dupErr || fmtErr ? "text-destructive" : ""}>
        Farmer ID *{" "}
        <span className="text-xs text-muted-foreground">{tx("(auto-generated, Super Admin can change)", "(অটো-জেনারেট, Super Admin পরিবর্তন করতে পারবে)")}</span>
        <span
          title={tx(
            "Format: 5-digit padded number, e.g. 00001. Inputs like 'F-00001', '1', '2026-00000001' are auto-normalized to 00001.",
            "ফরম্যাট: 5-digit, যেমন 00001। 'F-00001', '1', '2026-00000001' এর মতো ইনপুট স্বয়ংক্রিয়ভাবে 00001 হবে।"
          )}
          className="ml-1 inline-flex h-4 w-4 items-center justify-center rounded-full border text-[10px] cursor-help text-muted-foreground"
          aria-label="format help"
        >?</span>
      </Label>
      <Input
        value={f.member_no || ""}
        disabled={disabled || !isSuper}
        maxLength={5}
        inputMode="numeric"
        placeholder="00001"
        onChange={(e) => onChange(e.target.value.replace(/\D/g, "").slice(0, 5))}
        onBlur={onBlur}
        className={dupErr || fmtErr ? "border-destructive ring-2 ring-destructive/40 focus-visible:ring-destructive" : ""}
        data-testid="member-no-input"
      />
      {checking && <p className="mt-1 text-xs text-muted-foreground">Checking…</p>}
      {fmtErr && <p className="mt-1 text-xs text-destructive" role="alert">{fmtErr}</p>}
      {dupErr && <p className="mt-1 text-xs text-destructive" role="alert">{dupErr}</p>}
      {!isSuper && <p className="mt-1 text-xs text-muted-foreground">{tx("Only Super Admin can change.", "শুধু Super Admin পরিবর্তন করতে পারবে।")}</p>}
    </div>
  );
}

const EMPTY_FORM = {
  name_en: "", name_bn: "", father_name: "", mother_name: "", nid: "", mobile: "",
  address: "", voter_number: "", is_voter: false, member_no: "",
  office_id: "", status: "active",
  division_id: null, district_id: null, upazila_id: null, union_id: null,
  ward_id: null, village_id: null, mouza_id: null,
  nominee_name: "", nominee_mobile: "", nominee_relation: "",
  nominee_nid: "", nominee_address: "",
};

type FormState = typeof EMPTY_FORM & Record<string, any>;

type FormErrors = {
  name_en?: string;
  mobile?: string;
  nid?: string;
  office_id?: string;
  location?: string;
};

const farmerFormSchema = z.object({
  // Only English name is required (UI shows * only on this field). Other names are optional.
  name_en: z.string().trim().min(1, "Name (English) is required").max(100),
  name_bn: z.string().trim().max(100).optional().or(z.literal("")),
  father_name: z.string().trim().max(100).optional().or(z.literal("")),
  mother_name: z.string().trim().max(100).optional().or(z.literal("")),
  nid: z.string().trim().refine((v) => !v || /^\d{10,17}$/.test(v.replace(/\D/g, "")), "Invalid NID (10–17 digits)").optional().or(z.literal("")),
  mobile: z.string().trim().refine((v) => !v || /^\+?\d[\d\s-]{6,20}$/.test(v), "Invalid mobile number").optional().or(z.literal("")),
  member_no: z.string().trim().refine((v) => !v || /^\d{5}$/.test(v), "Farmer ID must be exactly 5 digits (e.g. 00001)").optional().or(z.literal("")),
  address: z.string().trim().max(250).optional().or(z.literal("")),
  voter_number: z.string().trim().refine((v) => !v || /^\d{5}$/.test(v), "Voter / Savings A/C No must be exactly 5 digits (e.g. 00001)").optional().or(z.literal("")),
  office_id: z.string().optional().or(z.literal("")),
});

function pickLocation(form: FormState): LocationValue {
  return {
    division_id: form.division_id, district_id: form.district_id,
    upazila_id: form.upazila_id, union_id: form.union_id,
    ward_id: form.ward_id, village_id: form.village_id, mouza_id: form.mouza_id,
    mouza_name: form.mouza_name ?? null,
    village: form.village ?? null,
  };
}

export default function Farmers() {
  const { t, tx } = useLang();
  const { officeId, isSuper, isAdmin } = useAuth();
  const nav = useNavigate();
  const [list, setList] = useState<any[]>([]);
  const [duesMap, setDuesMap] = useState<Record<string, { net_due: number; loan_due: number; irr_due: number; savings_bal: number }>>({});
  const [offices, setOffices] = useState<any[]>([]);
  const [q, setQ] = useState("");
  const [fatherQ, setFatherQ] = useState("");
  const [page, setPage] = useState(0);
  const [showDeleted, setShowDeleted] = useState(false);
  const [statusFilter, setStatusFilter] = useState<"all" | "active" | "inactive">("active");
  const [periodFilter, setPeriodFilter] = useState<"all" | "this_month" | "today">("all");
  const PAGE = 15;

  // Create
  const [open, setOpen] = useState(false);
  const [photo, setPhoto] = useState<File | null>(null);
  const [form, setForm] = useState<FormState>({ ...EMPTY_FORM, office_id: officeId ?? "" });
  const [createErr, setCreateErr] = useState<{ level: LocationLevel; key: string } | null>(null);
  const [createFieldErrors, setCreateFieldErrors] = useState<FormErrors>({});
  const createNameRef = useRef<HTMLInputElement>(null);

  // Edit
  const [editOpen, setEditOpen] = useState(false);
  const [editForm, setEditForm] = useState<FormState | null>(null);
  const [editPhoto, setEditPhoto] = useState<File | null>(null);
  const [editErr, setEditErr] = useState<{ level: LocationLevel; key: string } | null>(null);
  const [editFieldErrors, setEditFieldErrors] = useState<FormErrors>({});
  const editNameRef = useRef<HTMLInputElement>(null);
  const [saving, setSaving] = useState(false);
  const editReturnToRef = useRef<string | null>(null);


  // Unsaved-draft guard for the create form (survives accidental refresh/tab close)
  const createDirty = open && JSON.stringify({ ...form, office_id: "" }) !== JSON.stringify({ ...EMPTY_FORM, office_id: "" });
  const createGuard = useUnsavedFormGuard("farmer-create", form, createDirty);
  const editDirty = editOpen && editForm !== null;
  const editGuard = useUnsavedFormGuard("farmer-edit", editForm, editDirty);

  // Restore create-form draft once on mount (open dialog with prefilled data)
  const draftRestoredRef = useRef(false);
  useEffect(() => {
    if (draftRestoredRef.current) return;
    draftRestoredRef.current = true;
    const draft = createGuard.restore();
    if (draft && JSON.stringify({ ...draft, office_id: "" }) !== JSON.stringify({ ...EMPTY_FORM, office_id: "" })) {
      setForm(draft as FormState);
      setOpen(true);
    }
  }, []);

  useEffect(() => { document.title = `${t("farmers")} — ${t("appName")}`; load(); db.from("offices").select("id,name").then(r => setOffices(r.data ?? [])); }, [q, fatherQ, page, showDeleted, statusFilter, periodFilter]);
  useEffect(() => { setForm((f) => ({ ...f, office_id: officeId ?? f.office_id })); }, [officeId]);

  // Open the edit dialog when navigated with ?edit=<farmerId>
  const [searchParams, setSearchParams] = useSearchParams();
  useEffect(() => {
    const editId = searchParams.get("edit");
    if (editId && !editOpen) {
      const returnTo = searchParams.get("returnTo");
      editReturnToRef.current = returnTo;
      (async () => {
        const { data } = await db.from("farmers").select("*, offices(name)").eq("id", editId).maybeSingle();
        if (data) openEdit(data);
        const next = new URLSearchParams(searchParams);
        next.delete("edit");
        next.delete("returnTo");
        setSearchParams(next, { replace: true });
      })();
    }

    const s = searchParams.get("status");
    if (s === "active" || s === "inactive" || s === "all") setStatusFilter(s as any);
    const p = searchParams.get("period");
    if (p === "this_month" || p === "today" || p === "all") setPeriodFilter(p as any);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchParams]);

  // Scroll the failing dropdown into view when a hierarchy error appears.
  useEffect(() => {
    const lvl = createErr?.level ?? editErr?.level;
    if (!lvl) return;
    const el = document.querySelector(`[data-level="${lvl}"]`) as HTMLElement | null;
    el?.scrollIntoView({ behavior: "smooth", block: "center" });
  }, [createErr, editErr]);

  async function load() {
    // If the search includes dag-like tokens (comma / newline / whitespace
    // separated), also pull farmer_ids whose lands match ANY token. This lets
    // a search like "123, 124/A" find both single- and multi-dag lands.
    let dagFarmerIds: string[] = [];
    if (q && q.trim()) {
      const tokens = parseDagSearchTokens(q).slice(0, 10);
      if (tokens.length) {
        const orExpr = tokens.map((t) => `dag_no.ilike.%${t.replace(/[%,]/g, "")}%`).join(",");
        const { data: lr } = await db
          .from("lands")
          .select("farmer_id")
          .is("deleted_at", null)
          .or(orExpr)
          .limit(500);
        dagFarmerIds = Array.from(new Set((lr ?? []).map((x: any) => x.farmer_id).filter(Boolean)));
      }
    }

    let qy = db.from("farmers").select("*, offices(name)").order("created_at", { ascending: false }).range(page * PAGE, page * PAGE + PAGE - 1);
    qy = showDeleted ? qy.not("deleted_at", "is", null) : qy.is("deleted_at", null);
    if (statusFilter !== "all") qy = qy.eq("status", statusFilter);
    if (periodFilter !== "all") {
      const now = new Date();
      const from = periodFilter === "today"
        ? new Date(now.getFullYear(), now.getMonth(), now.getDate())
        : new Date(now.getFullYear(), now.getMonth(), 1);
      qy = qy.gte("created_at", from.toISOString());
    }
    if (q) {
      const base = `name_en.ilike.%${q}%,name_bn.ilike.%${q}%,father_name.ilike.%${q}%,farmer_code.ilike.%${q}%,account_number.ilike.%${q}%,member_no.ilike.%${q}%,mobile.ilike.%${q}%,nid.ilike.%${q}%`;
      const idClause = dagFarmerIds.length ? `,id.in.(${dagFarmerIds.join(",")})` : "";
      qy = qy.or(base + idClause);
    }
    if (fatherQ && fatherQ.trim()) {
      qy = qy.ilike("father_name", `%${fatherQ.trim()}%`);
    }
    const { data } = await qy;
    const farmers = data ?? [];
    setList(farmers);
    if (farmers.length) {
      const ids = farmers.map((f: any) => f.id);
      const { data: dues } = await db.rpc("farmer_dues_summary" as any);
      const map: Record<string, any> = {};
      (dues ?? []).forEach((d: any) => { if (ids.includes(d.farmer_id)) map[d.farmer_id] = d; });
      setDuesMap(map);
    } else {
      setDuesMap({});
    }
  }

  function clearFilters() {
    setQ("");
    setFatherQ("");
    setPage(0);
    setShowDeleted(false);
    setStatusFilter("active");
    setPeriodFilter("all");
    setSearchParams(new URLSearchParams(), { replace: true });
  }

  function levelLabel(level: LocationLevel) {
    const map: Record<LocationLevel, string> = {
      division: t("division"), district: t("district"), upazila: t("upazila"),
      union: t("union"), ward: t("ward"), village: t("village"), mouza: t("mouza"),
    };
    return map[level];
  }

  function buildErrMessage(key: string, level: LocationLevel) {
    const tpl = t(key as any) || "";
    return tpl.replace("{level}", levelLabel(level));
  }

  async function uploadPhoto(file: File): Promise<string | undefined> {
    const ext = file.name.split(".").pop();
    const path = `farmers/${Date.now()}.${ext}`;
    const { error } = await db.storage.from("farmer-photos").upload(path, file);
    if (error) { toast.error(error.message); return undefined; }
    return db.storage.from("farmer-photos").getPublicUrl(path).data.publicUrl;
  }

  function resetCreateForm() {
    setOpen(false);
    setPhoto(null);
    setCreateErr(null);
    setCreateFieldErrors({});
    setForm({ ...EMPTY_FORM, office_id: officeId ?? "" });
    setSaving(false);
    createGuard.clear();
  }

  function resetEditForm() {
    setEditOpen(false);
    setEditForm(null);
    setEditPhoto(null);
    setEditErr(null);
    setEditFieldErrors({});
    setSaving(false);
    editGuard.clear();
    const back = editReturnToRef.current;
    editReturnToRef.current = null;
    if (back && back.startsWith("/")) nav(back);
  }


  function commonValidate(f: FormState, setErrors: (errors: FormErrors) => void): boolean {
    const parsed = farmerFormSchema.safeParse({
      name_en: f.name_en,
      name_bn: f.name_bn ?? "",
      father_name: f.father_name ?? "",
      mother_name: f.mother_name ?? "",
      nid: f.nid ?? "",
      mobile: f.mobile ?? "",
      member_no: f.member_no ?? "",
      address: f.address ?? "",
      voter_number: f.voter_number ?? "",
      office_id: f.office_id ?? "",
    });

    const nextErrors: FormErrors = {};
    if (!parsed.success) {
      for (const issue of parsed.error.issues) {
        const key = issue.path[0] as keyof FormErrors | undefined;
        if (key && !nextErrors[key]) nextErrors[key] = issue.message;
      }
    }

    // Location is fully optional now — no chain enforcement.

    setErrors(nextErrors);
    if (Object.keys(nextErrors).length > 0) {
      const firstError = Object.values(nextErrors)[0];
      if (firstError) toast.error(firstError);
      return false;
    }
    return true;
  }

  async function save() {
    setCreateErr(null);
    setCreateFieldErrors({});
    if (!commonValidate(form, setCreateFieldErrors)) return;
    const v = validateLocationChain(pickLocation(form));
    if (v.ok === false) {
      setCreateErr({ level: v.level, key: "locationInvalidMissingParent" });
      setCreateFieldErrors((prev) => ({ ...prev, location: buildErrMessage("locationInvalidMissingParent", v.level) }));
      return;
    }
    // Duplicate check on member_no (Farmer ID) — always
    if (form.member_no) {
      const { data: dup } = await db.rpc("member_no_exists" as any, { _member_no: String(form.member_no).trim(), _exclude_id: null });
      if (dup === true) { toast.error(t("duplicateFarmerId")); return; }
    }

    // Auto-generate Farmer ID if empty (super admin can override above)
    let memberNo = form.member_no;
    if (!memberNo) {
      const { data: gen, error: genErr } = await db.rpc("generate_member_no" as any);
      if (genErr) { toast.error(genErr.message); return; }
      memberNo = String(gen ?? "");
    }

    setSaving(true);
    let photo_url: string | undefined;
    if (photo) {
      photo_url = await uploadPhoto(photo);
      if (!photo_url) { setSaving(false); return; }
    }
    const payload: any = toFarmerUpdatePayload(
      { ...form, member_no: memberNo, is_voter: !!form.voter_number, account_number: form.voter_number || null },
      photo_url ? { photo_url } : {}
    );
    if (form.office_id) payload.office_id = form.office_id;

    const { data, error } = await db.from("farmers").insert(payload).select().single();
    if (error) {
      setSaving(false);
      const lvl = parseLocationDbError(error.message);
      if (lvl) {
        setCreateErr({ level: lvl, key: "locationInvalidMismatch" });
        setCreateFieldErrors((prev) => ({ ...prev, location: buildErrMessage("locationInvalidMismatch", lvl) }));
      } else if ((error as any).code === "23505" || /duplicate key|unique constraint/i.test(error.message)) {
        const m = error.message.toLowerCase();
        if (m.includes("member_no") || m.includes("farmer_code")) toast.error(tx("Duplicate Farmer ID — this ID is already in use.", "Farmer ID আগেই ব্যবহৃত হয়েছে।"));
        else if (m.includes("voter_number") || m.includes("account_number")) toast.error(tx("Duplicate Voter / Savings A/C No — already in use.", "Voter / Savings A/C নম্বর আগেই ব্যবহৃত হয়েছে।"));
        else toast.error(tx("Duplicate value — this entry already exists.", "ডুপ্লিকেট মান — এই তথ্য আগেই আছে।"));
      } else toast.error(error.message);
      return;
    }
    if (data) await db.from("shares").insert({ farmer_id: data.id, balance: 0 });
    setSaving(false);
    toast.success(t("farmerAdded"));
    resetCreateForm();
    load();
  }

  function openEdit(row: any) {
    setEditErr(null); setEditPhoto(null);
    setEditForm({
      ...EMPTY_FORM,
      ...row,
      office_id: row.office_id ?? "",
    });
    setEditOpen(true);
  }

  async function saveEdit() {
    if (!editForm) return;
    setEditErr(null);
    setEditFieldErrors({});
    if (!commonValidate(editForm, setEditFieldErrors)) return;
    const v = validateLocationChain(pickLocation(editForm));
    if (v.ok === false) {
      setEditErr({ level: v.level, key: "locationInvalidMissingParent" });
      setEditFieldErrors((prev) => ({ ...prev, location: buildErrMessage("locationInvalidMissingParent", v.level) }));
      return;
    }
    if (editForm.member_no) {
      const { data: dup } = await db.rpc("member_no_exists" as any, { _member_no: String(editForm.member_no).trim(), _exclude_id: (editForm as any).id ?? null });
      if (dup === true) { toast.error(t("duplicateFarmerId")); return; }
    }

    setSaving(true);
    let photo_url: string | undefined;
    if (editPhoto) {
      photo_url = await uploadPhoto(editPhoto);
      if (!photo_url) { setSaving(false); return; }
    }
    const id = (editForm as any).id;
    const payload = toFarmerUpdatePayload(editForm as any, photo_url ? { photo_url } : {});
    if (import.meta.env.DEV) console.debug("[farmers.update] payload keys:", Object.keys(payload));
    const { error } = await db.from("farmers").update(payload as any).eq("id", id);
    if (error) {
      setSaving(false);
      const lvl = parseLocationDbError(error.message);
      if (lvl) {
        setEditErr({ level: lvl, key: "locationInvalidMismatch" });
        setEditFieldErrors((prev) => ({ ...prev, location: buildErrMessage("locationInvalidMismatch", lvl) }));
      } else if ((error as any).code === "23505" || /duplicate key|unique constraint/i.test(error.message)) {
        const m = error.message.toLowerCase();
        if (m.includes("member_no") || m.includes("farmer_code")) toast.error(tx("Duplicate Farmer ID — this ID is already in use.", "Farmer ID আগেই ব্যবহৃত হয়েছে।"));
        else if (m.includes("voter_number") || m.includes("account_number")) toast.error(tx("Duplicate Voter / Savings A/C No — already in use.", "Voter / Savings A/C নম্বর আগেই ব্যবহৃত হয়েছে।"));
        else toast.error(tx("Duplicate value — this entry already exists.", "ডুপ্লিকেট মান — এই তথ্য আগেই আছে।"));
      } else toast.error(error.message);
      return;
    }
    // Optimistic local update so voter_number / changed fields show immediately.
    setList((prev) => prev.map((r) => (r.id === id ? { ...r, ...payload } : r)));
    // Targeted refetch for the edited row to reconcile DB-trigger derived fields
    // (voter_number, farmer_code, joined relations) without a full table reload.
    const { data: fresh } = await db
      .from("farmers")
      .select("*, offices(name)")
      .eq("id", id)
      .maybeSingle();
    if (fresh) setList((prev) => prev.map((r) => (r.id === id ? fresh : r)));
    setSaving(false);
    toast.success(t("farmerUpdated"));
    resetEditForm();
  }

  async function remove(id: string) {
    const { error } = await db.from("farmers").update({ deleted_at: new Date().toISOString() } as any).eq("id", id);
    if (error) return toast.error(error.message);
    toast.success(t("farmerArchived"));
    load();
  }

  async function restore(id: string) {
    const { error } = await db.from("farmers").update({ deleted_at: null } as any).eq("id", id);
    if (error) return toast.error(error.message);
    toast.success(t("farmerRestored"));
    load();
  }

  async function permanentDelete(id: string) {
    const { data, error } = await db.rpc("farmer_permanent_delete", { _farmer_id: id });
    if (error) return toast.error(error.message);
    const res = (data as any)?.result ?? data;
    if (!res?.ok) {
      return toast.error(res?.message || tx("Cannot permanently delete this farmer.", "এই ফার্মার পারমানেন্ট ডিলিট করা যাবে না।"));
    }
    toast.success(res.message || tx("Farmer permanently deleted.", "ফার্মার পারমানেন্টভাবে ডিলিট করা হয়েছে।"));
    load();
  }


  async function toggleStatus(id: string, current: string) {
    const next = current === "active" ? "inactive" : "active";
    setList((prev) => prev.map((r) => (r.id === id ? { ...r, status: next } : r)));
    const { error } = await db.from("farmers").update({ status: next } as any).eq("id", id);
    if (error) { toast.error(error.message); load(); return; }
    toast.success(next === "active" ? tx("Member activated", "সদস্য সক্রিয় করা হয়েছে") : tx("Member marked inactive", "সদস্য নিষ্ক্রিয় করা হয়েছে"));
  }

  // ---------- Reusable form fields ----------
  const renderFormFields = ({
    f, setF, photoFile, setPhotoFile, err, fieldErrors, disabled, nameInputRef,
  }: {
    f: FormState;
    setF: (next: FormState) => void;
    photoFile: File | null;
    setPhotoFile: (p: File | null) => void;
    err: { level: LocationLevel; key: string } | null;
    fieldErrors: FormErrors;
    disabled: boolean;
    nameInputRef?: RefObject<HTMLInputElement | null>;
  }) => {
    return (
      <div className="grid grid-cols-2 gap-3">
        <div>
          <Label className={fieldErrors.name_en ? "text-destructive" : ""}>{t("nameEn")} *</Label>
          <Input
            ref={nameInputRef}
            value={f.name_en}
            disabled={disabled}
            maxLength={100}
            aria-invalid={!!fieldErrors.name_en || undefined}
            className={fieldErrors.name_en ? "border-destructive ring-2 ring-destructive/40 focus-visible:ring-destructive" : ""}
            onChange={e => setF({ ...f, name_en: e.target.value })}
          />
          {fieldErrors.name_en && <p className="mt-1 text-xs text-destructive">{fieldErrors.name_en}</p>}
        </div>
        <div><Label>{t("nameBn")}</Label><Input value={f.name_bn} disabled={disabled} maxLength={100} onChange={e => setF({ ...f, name_bn: e.target.value })} /></div>
        <div><Label>{t("fatherName")}</Label><Input value={f.father_name} disabled={disabled} maxLength={100} onChange={e => setF({ ...f, father_name: e.target.value })} /></div>
        <div><Label>{t("motherName")}</Label><Input value={f.mother_name} disabled={disabled} maxLength={100} onChange={e => setF({ ...f, mother_name: e.target.value })} /></div>
        <div>
          <Label className={fieldErrors.nid ? "text-destructive" : ""}>{t("nid")}</Label>
          <Input value={f.nid} disabled={disabled} inputMode="numeric" maxLength={17} onChange={e => setF({ ...f, nid: e.target.value })} className={fieldErrors.nid ? "border-destructive ring-2 ring-destructive/40 focus-visible:ring-destructive" : ""} />
          {fieldErrors.nid && <p className="mt-1 text-xs text-destructive">{fieldErrors.nid}</p>}
        </div>
        <div>
          <Label className={fieldErrors.mobile ? "text-destructive" : ""}>{t("mobile")}</Label>
          <Input value={f.mobile} disabled={disabled} inputMode="tel" maxLength={20} onChange={e => setF({ ...f, mobile: e.target.value })} className={fieldErrors.mobile ? "border-destructive ring-2 ring-destructive/40 focus-visible:ring-destructive" : ""} />
          {fieldErrors.mobile && <p className="mt-1 text-xs text-destructive">{fieldErrors.mobile}</p>}
        </div>
        <FarmerIdField f={f} setF={setF} disabled={disabled} isSuper={isSuper} currentId={f.id ?? null} />
        <VoterSavingsField f={f} setF={setF} disabled={disabled} isSuper={isSuper} />
        <div>
          <Label>{t("office")}</Label>
          <Select value={f.office_id ? f.office_id : "__none__"} onValueChange={v => setF({ ...f, office_id: v === "__none__" ? "" : v })} disabled={disabled}>
            <SelectTrigger><SelectValue placeholder="—" /></SelectTrigger>
            <SelectContent>
              <SelectItem value="__none__">—</SelectItem>
              {offices.map(o => <SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}
            </SelectContent>
          </Select>
        </div>
        <div className="col-span-2"><Label>{t("address")}</Label><Input value={f.address} disabled={disabled} maxLength={250} onChange={e => setF({ ...f, address: e.target.value })} /></div>

        {/* Nominee section */}
        <div className="col-span-2 border-t pt-3 mt-1">
          <div className="text-xs font-semibold text-muted-foreground mb-2">
            {tx("Nominee Information", "নমিনির তথ্য")}
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>{tx("Nominee Name", "নমিনির নাম")}</Label>
              <Input value={f.nominee_name ?? ""} disabled={disabled} maxLength={100}
                onChange={e => setF({ ...f, nominee_name: e.target.value })} />
            </div>
            <div>
              <Label>{tx("Nominee Mobile", "নমিনির মোবাইল")}</Label>
              <Input value={f.nominee_mobile ?? ""} disabled={disabled} inputMode="tel" maxLength={20}
                onChange={e => setF({ ...f, nominee_mobile: e.target.value })} />
            </div>
            <div>
              <Label>{tx("Relation", "সম্পর্ক")}</Label>
              <Select
                value={f.nominee_relation || ""}
                disabled={disabled}
                onValueChange={(v) => setF({ ...f, nominee_relation: v })}
              >
                <SelectTrigger>
                  <SelectValue placeholder={tx("Select relation", "সম্পর্ক নির্বাচন করুন")} />
                </SelectTrigger>
                <SelectContent>
                  {[
                    ["son", "ছেলে"],
                    ["daughter", "মেয়ে"],
                    ["wife", "স্ত্রী"],
                    ["husband", "স্বামী"],
                    ["father", "পিতা"],
                    ["mother", "মাতা"],
                    ["brother", "ভাই"],
                    ["sister", "বোন"],
                    ["other", "অন্যান্য"],
                  ].map(([en, bn]) => (
                    <SelectItem key={en} value={bn}>{tx(en.charAt(0).toUpperCase() + en.slice(1), bn)}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>{tx("Nominee NID", "নমিনির এনআইডি")}</Label>
              <Input value={f.nominee_nid ?? ""} disabled={disabled} inputMode="numeric" maxLength={17}
                onChange={e => setF({ ...f, nominee_nid: e.target.value })} />
            </div>
            <div className="col-span-2">
              <Label>{tx("Nominee Address", "নমিনির ঠিকানা")}</Label>
              <Input value={f.nominee_address ?? ""} disabled={disabled} maxLength={250}
                onChange={e => setF({ ...f, nominee_address: e.target.value })} />
            </div>
          </div>
        </div>


        <div className="col-span-2 border-t pt-3 mt-1">
          <div className="text-xs font-medium text-muted-foreground mb-2">
            {t("locationStrictHint")}
          </div>
          {(err || fieldErrors.location) && (
            <Alert variant="destructive" className="mb-3" role="alert" aria-live="assertive">
              <AlertTriangle className="h-4 w-4" />
              <AlertTitle>{t("locationInvalidTitle")}</AlertTitle>
              <AlertDescription data-testid="location-error" data-level={err?.level}>
                {fieldErrors.location ?? (err ? <><span className="font-semibold">{levelLabel(err.level)}:</span>{" "}{buildErrMessage(err.key, err.level)}</> : null)}
              </AlertDescription>
            </Alert>
          )}
          <LocationPicker
            mouzaOnly
            value={pickLocation(f)}
            onChange={(loc) => setF({ ...f, ...loc })}
            errorLevel={(err?.level as any) ?? null}
            errorMessage={fieldErrors.location ?? (err ? buildErrMessage(err.key, err.level) : null)}
            labels={{
              division: t("division"), district: t("district"),
              upazila: t("upazila"), village: t("village"),
            }}
          />
        </div>
        <div className="col-span-2"><Label>{t("photo")}</Label><Input type="file" accept="image/*" disabled={disabled} onChange={e => setPhotoFile(e.target.files?.[0] ?? null)} />
          {photoFile && <div className="text-xs text-muted-foreground mt-1">{photoFile.name}</div>}
        </div>
      </div>
    );
  };

  return (
    <>
      <PageHeader title={t("farmers")} actions={
        <div className="flex items-center gap-2 flex-wrap">
          <Button type="button" variant="outline" size="sm" onClick={downloadFarmerTemplate} title={t("downloadTemplateTip")}>
            <Download className="h-4 w-4 mr-1" /> {t("template")}
          </Button>
          <Button type="button" variant="outline" size="sm" onClick={() => nav("/farmers/import")} title={t("openBulkImporterTip")}>
            <Upload className="h-4 w-4 mr-1" /> {t("bulkImport")}
          </Button>
          <Dialog open={open} onOpenChange={(o) => { if (!o && !saving) resetCreateForm(); else setOpen(o); }}>
          <DialogTrigger asChild><Button><Plus className="h-4 w-4 mr-1" />{t("addNew")}</Button></DialogTrigger>
          <DialogContent
            className="max-w-2xl max-h-[85vh] overflow-y-auto"
            onOpenAutoFocus={(e) => {
              e.preventDefault();
              setTimeout(() => createNameRef.current?.focus(), 50);
            }}
          >
            <DialogHeader>
              <DialogTitle>{t("addNew")} — {t("farmers")}</DialogTitle>
              <DialogDescription>{tx("Fill in farmer details below.", "নিচে কৃষকের তথ্য পূরণ করুন।")}</DialogDescription>
            </DialogHeader>
            <div>
              {renderFormFields({
                f: form,
                setF: (next) => { setForm(next); if (createErr) setCreateErr(null); if (Object.keys(createFieldErrors).length) setCreateFieldErrors({}); },
                photoFile: photo,
                setPhotoFile: setPhoto,
                err: createErr,
                fieldErrors: createFieldErrors,
                disabled: saving,
                nameInputRef: createNameRef,
              })}
              <DialogFooter className="mt-6">
                <Button type="button" variant="outline" onClick={resetCreateForm} disabled={saving}>{t("cancel")}</Button>
                <Button type="button" onClick={() => { if (!saving) save(); }} disabled={saving}>{saving ? <><Loader2 className="h-4 w-4 mr-1 animate-spin" />{t("save")}</> : t("save")}</Button>
              </DialogFooter>
            </div>
          </DialogContent>
        </Dialog>
        </div>
      } />

      <Card className="p-4 mb-4">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="relative max-w-md flex-1">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder={t("search") + tx(" / Dag (123, 124/A)…", " / দাগ (123, 124/A)…")} value={q} onChange={e => { setQ(e.target.value); setPage(0); }} className="pl-9" />
          </div>
          <div className="relative max-w-xs flex-1">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder={tx("Search by father's name…", "পিতার নাম দিয়ে খুঁজুন…")} value={fatherQ} onChange={e => { setFatherQ(e.target.value); setPage(0); }} className="pl-9" />
          </div>
          <div className="flex items-center gap-3 flex-wrap">
            <Select value={statusFilter} onValueChange={(v: any) => { setStatusFilter(v); setPage(0); const n = new URLSearchParams(searchParams); if (v === "all") n.delete("status"); else n.set("status", v); setSearchParams(n, { replace: true }); }}>
              <SelectTrigger className="w-[160px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="active">{tx("Active only", "শুধু সক্রিয়")}</SelectItem>
                <SelectItem value="inactive">{tx("Inactive only", "শুধু নিষ্ক্রিয়")}</SelectItem>
                <SelectItem value="all">{tx("All statuses", "সব স্ট্যাটাস")}</SelectItem>
              </SelectContent>
            </Select>
            <Select value={periodFilter} onValueChange={(v: any) => { setPeriodFilter(v); setPage(0); const n = new URLSearchParams(searchParams); if (v === "all") n.delete("period"); else n.set("period", v); setSearchParams(n, { replace: true }); }}>
              <SelectTrigger className="w-[160px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{tx("Any period", "যেকোনো সময়")}</SelectItem>
                <SelectItem value="this_month">{tx("This month", "এই মাস")}</SelectItem>
                <SelectItem value="today">{tx("Today", "আজ")}</SelectItem>
              </SelectContent>
            </Select>
            {isSuper && (
              <label className="flex items-center gap-2 text-sm">
                <Switch checked={showDeleted} onCheckedChange={(v) => { setShowDeleted(v); setPage(0); }} />
                <span>{t("showArchived")}</span>
              </label>
            )}
            <Button variant="ghost" size="sm" onClick={clearFilters}>{tx("Clear filters", "ফিল্টার মুছুন")}</Button>
          </div>
        </div>
      </Card>

      <Card>
        <div className="[&_table]:min-w-[900px]">
        <Table>
          <TableHeader><TableRow>
            <TableHead>{t("farmerIdLabel")}</TableHead><TableHead>{t("voterNumber")}</TableHead><TableHead>{t("farmerName")}</TableHead>
            <TableHead>{t("fatherName")}</TableHead>
            <TableHead>{t("mobile")}</TableHead><TableHead>{t("village")}</TableHead>
            <TableHead>{t("office")}</TableHead><TableHead>{t("status")}</TableHead>
            <TableHead className="text-right">{t("dueAmount")}</TableHead>
            <TableHead className="text-right">{t("actions")}</TableHead>
          </TableRow></TableHeader>
          <TableBody>
            {list.map(f => (
              <TableRow key={f.id} className="cursor-pointer" onClick={() => nav(`/farmers/${f.id}`)}>
                <TableCell className="font-mono text-xs">{f.member_no ? formatId5(f.member_no) : "—"}</TableCell>
                <TableCell className="font-mono text-xs">{f.voter_number ? formatId5(f.voter_number) : "—"}</TableCell>
                <TableCell className="max-w-[220px]">
                  <TruncateText className="font-medium block">{f.name_en}</TruncateText>
                  {f.name_bn && <TruncateText className="text-xs text-muted-foreground block">{f.name_bn}</TruncateText>}
                </TableCell>
                <TableCell className="max-w-[160px]"><TruncateText>{f.father_name || "—"}</TruncateText></TableCell>
                <TableCell className="max-w-[140px]"><TruncateText>{f.mobile}</TruncateText></TableCell>
                <TableCell className="max-w-[160px]"><TruncateText>{f.village || f.villages?.name_bn || f.villages?.name || "—"}</TruncateText></TableCell>
                <TableCell className="text-xs max-w-[160px]"><TruncateText>{f.offices?.name}</TruncateText></TableCell>
                <TableCell onClick={(e) => e.stopPropagation()}>
                  {isAdmin && !f.deleted_at ? (
                    <Badge
                      variant={f.status === "active" ? "default" : "secondary"}
                      className="cursor-pointer select-none"
                      title={tx("Click to toggle active/inactive", "ক্লিক করে সক্রিয়/নিষ্ক্রিয় করুন")}
                      onClick={() => toggleStatus(f.id, f.status)}
                    >
                      {f.status === "active" ? tx("Active", "সক্রিয়") : tx("Inactive", "নিষ্ক্রিয়")}
                    </Badge>
                  ) : (
                    <Badge variant={f.status === "active" ? "default" : "secondary"}>{f.status === "active" ? tx("Active", "সক্রিয়") : tx("Inactive", "নিষ্ক্রিয়")}</Badge>
                  )}
                </TableCell>
                <TableCell className="text-right">
                  {(() => {
                    const d = duesMap[f.id];
                    const v = d ? Number(d.net_due) : 0;
                    return <span className={v > 0 ? "due-text font-semibold" : "text-muted-foreground"}>{money(v)}</span>;
                  })()}
                </TableCell>
                <TableCell className="text-right" onClick={(e) => e.stopPropagation()}>
                  <div className="flex items-center justify-end gap-1">
                    <ViewButton title={t("viewTip")} onClick={() => nav(`/farmers/${f.id}`)} />
                    {!f.deleted_at && <EditButton title={t("editTip")} onClick={() => nav(`/farmers/${f.id}`)} />}
                    {isSuper && f.deleted_at && (
                      <>
                        <Button size="sm" variant="outline" onClick={() => restore(f.id)}>{t("restore")}</Button>
                        <PermanentDeleteDialog
                          farmerId={f.id}
                          onDeleted={load}
                          triggerLabel={tx("Delete permanently", "পারমানেন্ট ডিলিট")}
                        />
                      </>
                    )}
                    {isSuper && !f.deleted_at && (
                      <AlertDialog>
                        <AlertDialogTrigger asChild>
                          <DeleteButton title={t("deleteTipShort")} />
                        </AlertDialogTrigger>
                        <AlertDialogContent>
                          <AlertDialogHeader>
                            <AlertDialogTitle>{t("archiveFarmerTitle")}</AlertDialogTitle>
                            <AlertDialogDescription>
                              {t("archiveFarmerDesc").replace("{code}", String(f.farmer_code ?? f.member_no ?? ""))}
                            </AlertDialogDescription>
                          </AlertDialogHeader>
                          <AlertDialogFooter>
                            <AlertDialogCancel>{t("cancel")}</AlertDialogCancel>
                            <AlertDialogAction onClick={() => remove(f.id)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">{t("archive")}</AlertDialogAction>
                          </AlertDialogFooter>
                        </AlertDialogContent>
                      </AlertDialog>
                    )}
                  </div>
                </TableCell>
              </TableRow>
            ))}
            {list.length === 0 && <TableRow><TableCell colSpan={10} className="text-center text-muted-foreground py-6">{t("noData")}</TableCell></TableRow>}
          </TableBody>
        </Table>
        </div>
        <div className="flex items-center justify-between p-3 border-t">
          <div className="text-xs text-muted-foreground">{t("pageNum").replace("{n}", String(page + 1))}</div>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" disabled={page === 0} onClick={() => setPage(p => p - 1)}>{t("prev")}</Button>
            <Button size="sm" variant="outline" disabled={list.length < PAGE} onClick={() => setPage(p => p + 1)}>{t("next")}</Button>
          </div>
        </div>
      </Card>

      {/* Edit dialog */}
      <Dialog open={editOpen} onOpenChange={(o) => { if (!o && !saving) resetEditForm(); else setEditOpen(o); }}>
        <DialogContent
          className="max-w-2xl max-h-[85vh] overflow-y-auto"
          onOpenAutoFocus={(e) => {
            e.preventDefault();
            setTimeout(() => editNameRef.current?.focus(), 50);
          }}
        >
          <DialogHeader>
            <DialogTitle>{t("edit")} — {t("farmers")}</DialogTitle>
            <DialogDescription>{tx("Update farmer details below.", "নিচে কৃষকের তথ্য আপডেট করুন।")}</DialogDescription>
          </DialogHeader>
          {editForm && (
            <div>
              {renderFormFields({
                f: editForm,
                setF: (next) => { setEditForm(next); if (editErr) setEditErr(null); if (Object.keys(editFieldErrors).length) setEditFieldErrors({}); },
                photoFile: editPhoto,
                setPhotoFile: setEditPhoto,
                err: editErr,
                fieldErrors: editFieldErrors,
                disabled: saving,
                nameInputRef: editNameRef,
              })}
              <DialogFooter className="mt-6">
                <Button type="button" variant="outline" onClick={resetEditForm} disabled={saving}>{t("cancel")}</Button>
                <Button type="button" onClick={() => { if (!saving) saveEdit(); }} disabled={saving}>{saving ? <><Loader2 className="h-4 w-4 mr-1 animate-spin" />{t("save")}</> : t("save")}</Button>
              </DialogFooter>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
