REVOKE EXECUTE ON FUNCTION public.block_txn_for_inactive_farmer() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_borga_allocation() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ensure_irrigation_invoice_office() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.farmers_sync_voter_number() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_irrigation_rate_change() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_land_change() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_invoice_snapshot() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recompute_loan_status_after_payment() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.savings_check_withdraw_balance() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.current_user_office() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_permission(uuid, text, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, app_role) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin_or_super(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_developer(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_developer_user(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.log_developer_access(text, boolean, jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.next_voucher_no(uuid, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.post_asset_depreciation_journal(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_irrigation_invoice(uuid, text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.run_monthly_depreciation_batch(date) FROM anon, PUBLIC;