// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { sharedSessionStorage } from '@/lib/sharedSessionStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Session lives in sessionStorage (dies when the whole browser closes) but
    // is shared across open tabs via BroadcastChannel — see sharedSessionStorage.
    storage: sharedSessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});